### ISSUE TITLE
`GrpcClientMetricAutoConfiguration` breaks system metrics

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [grpc-ecosystem/grpc-spring#992] opened 2023-11-17 13:33 UTC
**The context**

Adding `grpc-client-spring-boot-starter` as a dependency breaks micrometer system metrics. (e.g. `system_cpu_usage` is no longer present)

**The bug**

`GrpcClientMetricAutoConfiguration` breaks bean post-processing for micrometer registry beans. [This blog post](https://blog.monosoul.dev/2021/04/02/who-stole-my-spring-boot-system-metrics/) has a good explanation.

**Stacktrace and logs**
```
2023-11-17 14:25:06.469  INFO 83909 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'prometheusMeterRegistry' of type [io.micrometer.prometheus.PrometheusMeterRegistry] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

**The application's environment**

Which versions do you use?
* Spring boot:  2.7.14
* grpc-java: 1.51.0
* grpc-spring-boot-starter: 2.14.0.RELEASE
* java: 17 (amd64)
* micrometer-core: 1.9.13
* spring-boot-starter-actuator: 2.7.14

**Additional context**

excluding the autoconfiguration class fixes the issue at the cost of grpc metrics

```java
@SpringBootApplication(exclude = {
        GrpcClientMetricAutoConfiguration.class
})
```

**Comment by ST-DDT** [comment] 2023-11-25 14:35
Duplicate of #859.
Could you please check whether #907 fixes the issue for you? (And comment there)

- #859
- #907

**Closed by ST-DDT** 2023-11-25 14:35 UTC
Labels: bug
