### ISSUE TITLE
Is there a time line for v3.0.0 release

### ISSUE THREAD

**Issue by thirumurthis** [grpc-ecosystem/grpc-spring#1012] opened 2023-12-07 06:15 UTC
**When can the we expect the v3.0.0 release with the SpringBoot 3+ support.**

In the Version notes it is mentioned as Nov 2023, if there is a time line for that release it helps.

**Comment by ST-DDT** [comment] 2023-12-08 10:15
Duplicate of https://github.com/grpc-ecosystem/grpc-spring/issues/953

**Closed by ST-DDT** 2023-12-08 10:15 UTC
Labels: question
